import type { Metadata } from "next";
import { Sofia_Sans, Courgette } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// Load Sofia Sans from Google Fonts
const sofiaSans = Sofia_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-sofia-sans",
});

// Load Pangram as a local font
const pangram = localFont({
  src: [
    {
      path: "../../public/fonts/Pangram-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Pangram-Bold.otf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-pangram",
  display: "swap",
});

// Load Courgette from Google Fonts
const courgette = Courgette({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-courgette",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${sofiaSans.variable} ${pangram.variable} font-sans   ${courgette.variable} `}
      >
        {children}
      </body>
    </html>
  );
}
